### ISSUE TITLE
Fix colors

### ISSUE THREAD

**Issue by KilroyWasHere-cs-j** [KilroyWasHere-cs-j/ScoutEye-Download-Webpage#7]
Kinda goes with styling, but the colors need to be fixed.

**Comment by KilroyWasHere-cs-j** [comment]
Ask Amory for what the teams colors are.

**Comment by KilroyWasHere-cs-j** [comment]
Colors fixed.

**Comment by Drresi** [comment]
if we need to reopen this and get the actual team colors we can, but i think it is a good baseline

**Comment by KilroyWasHere-cs-j** [comment]
Reopened: Update to team colors.

**Comment by Drresi** [comment]
yellow - R245 g195 b0
red - R110, G0,B0

**Comment by KilroyWasHere-cs-j** [comment]
Convert to hex.

**Comment by Drresi** [comment]
gonna push a new branch cause you can't use the right fucking colors
